# kubectl create -f app-secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: redis
type: Opaque
data:
  password: T3JhQDIwMjEucGFzc3dk

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: redis
type: Opaque
data:
  password: STNnUXFGbHh4VQ==
