# kubectl create configmap demo-config --from-file=config.yaml -n redis
Database:
  DBType: mysql
  UserName: time
  Password: Ora@2021.passwd
  Host: 132.145.92.220:3306
  DBName: microdb
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
Redis:
  Addr: 132.145.92.220:6379
  Password: 
