# kubectl create configmap demo-config --from-file=config.yaml -n redis
Database:
  DBType: mysql
  UserName: time
  Password: Ora@2021.passwd    # root Bn@Oracle.admin.19
  Host: mysql:3306
  DBName: microdb
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
Redis:
  Addr: redis-master.redis:6379
  Password: I3gQqFlxxU
